version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: container-db
    ports:
      - "127.0.0.1:9876:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: default_db
    healthcheck:
      test: pg_isready -U admin -d default_db
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./server/database/migrations:/migrations
    command:
      ["-path", "/migrations", "-database", "postgresql://admin:root@db:5432/default_db?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

# TODO: add env variables and maybe a makeFile