version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "6060:6060"
    env_file:
      - .env
    depends_on:
      - migrate

  db:
    image: postgres:latest
    container_name: container-db
    ports:
      - "127.0.0.1:9876:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./server/database/migrations:/migrations
    command:
      ["-path", "/migrations", "-database", "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

# TODO: add a makeFile